apiVersion: v1
kind: Service
metadata:
  labels:
    app: kubesphere
    component: ubd-gcp-fe
  name: ubd-gcp-fe
  namespace: ubd-gcp
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: kubesphere
    component: ubd-gcp-fe
    tier: frontend
  sessionAffinity: None
  type: ClusterIP
