apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubesphere
    component: ubd-gcp-fe
    tier: frontend
  name: ubd-gcp-fe
  namespace: ubd-gcp
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: kubesphere
      component: ubd-gcp-fe
      tier: frontend
  template:
    metadata:
      labels:
        app: kubesphere
        component: ubd-gcp-fe
        tier: frontend
    spec:
      containers:
        - image: $REGISTRY/$HARBOR_NAMESPACE/$APP_NAME:$BUILD_NUMBER
          imagePullPolicy: IfNotPresent
          name: ubd-gcp-fe
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: harbor